#**************************************
# media 
#*************************************
#background : public/media/alaska.jpg
#**************************************
# style 
#*************************************
style :
 couleurFondLibre: blue-grey
 couleurFondReservee: red
 couleurTexteLibre: grey-text
 couleurTexteReserve: white-text
 couleurFormeLibre: blue-grey
 couleurFormeReservee: red
#**************************************
#routes à suivre
#**************************************
# l'appel donne le nom de la fonction
# puis les paramètres éventuels
#**************************************
#Nom de la route :
# classe : nom de la classe
# operation : nom de l'opération
# niveauSecurité : valeur du niveau requis
# variable :
#  nomVariable1 : son nom
#....
#  nomVariablen : son nom
#**************************************
IGN.html :
 classe : ControlleurMap
 operation : executeCarte
 niveauSecurité : 0
 variable :
  cible : IGN
addCarte.html :
 classe : ControlleurMap
 operation : executeCarte
 niveauSecurité : 2
 variable :
  cible : Leaflet2
leaflet2.html :
 classe : ControlleurMap
 operation : executeCarte
 niveauSecurité : 0
 variable :
  cible : Leaflet2
accueil.html :
 classe : Controlleur
 operation : montre
 niveauSecurité : 0
 variable :
  classe : AccueilView
  action : show  
inscription.html :
 classe : Controlleur
 operation : montre
 niveauSecurité : 0
 variable :
  classe : InscriptionView
  action : show
enregistrement.html :
 classe : ControlleurAbonne
 operation : ajoute
 niveauSecurité : 0
 variable : 
  null
accesreserve.html :
 classe : Controlleur
 operation : montre
 niveauSecurité : 0
 variable :
  classe : AccesReserveView
  action : show   
zonereservee.html :
 classe : ControlleurAccess
 operation : validAccesReserve
 niveauSecurité : 0
 variable :
  Null  
sortirZoneReservee.html :
 classe : ControlleurAccess
 operation : sortirAccesReserve
 niveauSecurité : 0
 variable :
  Null
verifUser :
 classe : VerifAjax
 operation : user
 niveauSecurité : 0
 variable :
  Null
addLigne:
 classe : ControlleurLigne
 operation : addLigne
 niveauSecurité : 0
 variable :
  Null
lireTousFronts:
 classe : ControlleurFront
 operation : lireTousFronts
 niveauSecurité : 0
 variable :
  Null 
creerFrontsJSON:
 classe : ControlleurFront
 operation : jsonTousFronts
 niveauSecurité : 0
 variable :
  Null   
lireFronJSON:
 classe : ControlleurFront
 operation : lireJSON
 niveauSecurité : 0
 variable :
  Null   
